apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flask-cicd

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml


commonLabels:
  app.kubernetes.io/name: flask-cicd
  app.kubernetes.io/managed-by: fleet
  app.kubernetes.io/part-of: flask-cicd-gitops


images:
  - name: maisara99/flask-cicd
    newTag: latest
